name: Build and Test Assembly

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest   # Setează runner-ul pe Windows

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run hello.exe
        run: |
          .\hello.exe
