name: Build and Test Assembly

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted   # Setează runner-ul

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run hello.exe
        run: |
          .\hello.exe
